name: Process Novel Chapters

on:
  push:
    paths:
      - '*.txt'

jobs:
  process-novels:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install chardet

    - name: Create necessary directories
      run: |
        mkdir -p novel novel_already

    - name: Process TXT novels
      run: |
        python .github/scripts/process_novels.py

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Auto-processed novels: Split chapters and organized files" || echo "No changes to commit"
        git push        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Auto-processed novels: Split chapters and organized files" || echo "No changes to commit"
        git push
